CREATE TABLE TASK_RESULTS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Identifiant unique pour chaque tâche
    PARAM NUMBER NOT NULL,
    -- Paramètre utilisé pour la tâche (n)
    DESCRIPTION VARCHAR2(255),
    -- Description de la tâche (facultatif)
    DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Date de création de la tâche
    PRIMARY KEY (ID)
);
----------
----------
------
----
-----
----
-----
-------
CREATE TABLE FIBONACCI_SEQUENCE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Identifiant unique, même que dans eluard
    RESULT VARCHAR2(4000),
    -- Séquence de Fibonacci stockée sous forme de chaîne
    PRIMARY KEY (ID)
);